"""Initial migration

Revision ID: 478b0e9fc705
Revises: 
Create Date: 2025-10-21 15:16:27.816324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478b0e9fc705'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'extracting', 'diffing', 'analyzing', 'generating', 'completed', 'failed', name='case_status'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_changes', sa.Integer(), nullable=True),
    sa.Column('semantic_changes_count', sa.Integer(), nullable=True),
    sa.Column('technical_changes_count', sa.Integer(), nullable=True),
    sa.Column('overall_impact', sa.Enum('low', 'medium', 'high', name='impact_level'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('html_report_path', sa.String(), nullable=True),
    sa.Column('pdf_report_path', sa.String(), nullable=True),
    sa.Column('json_report_path', sa.String(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('added', 'removed', 'modified', name='change_type'), nullable=False),
    sa.Column('old_text', sa.Text(), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=True),
    sa.Column('context_before', sa.Text(), nullable=True),
    sa.Column('context_after', sa.Text(), nullable=True),
    sa.Column('is_semantic_change', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('dates', 'obligations', 'financial', 'conditions', 'parties', 'technical', 'other', name='change_category'), nullable=True),
    sa.Column('impact', sa.Enum('low', 'medium', 'high', name='impact_level'), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('old_embedding', sa.JSON(), nullable=True),
    sa.Column('new_embedding', sa.JSON(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['comparison_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('base', 'target', name='document_type'), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('structure', sa.JSON(), nullable=True),
    sa.Column('is_scanned', sa.Integer(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['comparison_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparison_documents')
    op.drop_table('comparison_changes')
    op.drop_table('comparison_cases')
    # ### end Alembic commands ###

